spring.application.name=onlineBanking

# PostgreSQL Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQL Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Dynamic Port for Render
server.port=${PORT:8080}